version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: password
      POSTGRES_DB: boardcollab
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    depends_on:
      - postgres
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
volumes:
  postgres_data:
  