version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: collabboard
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
