# fly.toml app configuration file generated for backend-red-fog-3909 on 2025-07-31T12:26:05-04:00

app = 'backend-red-fog-3909'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 5000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "15s"
    method = "get"
    path = "/health"
    protocol = "http"
